name: Build Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual trigger

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Change from 3.11 to 3.10
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install customtkinter pyinstaller python-libtorrent
        
    - name: Create __init__.py files
      run: |
        echo. > gui/__init__.py
        echo. > network/__init__.py
        
    - name: Build executable
      run: |
        pyinstaller --onefile --noconsole --name p2pnotes gui/main_window.py
        
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: p2pnotes-windows-exe
        path: dist/p2pnotes.exe
